/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Expense {
  'id' : string,
  'expenseDate' : string,
  'title' : string,
  'billImage' : ExternalBlob,
  'tripId' : string,
  'notes' : [] | [string],
  'category' : ExpenseCategory,
  'amount' : number,
}
export type ExpenseCategory = { 'Food' : null } |
  { 'Travel' : null } |
  { 'Hotel' : null } |
  { 'Other' : null };
export type ExternalBlob = Uint8Array;
export interface Trip {
  'id' : string,
  'endDate' : string,
  'name' : string,
  'description' : [] | [string],
  'startDate' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addExpense' : ActorMethod<
    [
      string,
      number,
      ExpenseCategory,
      string,
      ExternalBlob,
      [] | [string],
      string,
    ],
    Expense
  >,
  'createTrip' : ActorMethod<[string, string, string, [] | [string]], Trip>,
  'debugPrintTripsMap' : ActorMethod<[], undefined>,
  'deleteExpense' : ActorMethod<[string], undefined>,
  'deleteTrip' : ActorMethod<[string], undefined>,
  'getAllTrips' : ActorMethod<[], Array<Trip>>,
  'getExpensesByTripId' : ActorMethod<[string], Array<Expense>>,
  'getTripById' : ActorMethod<[string], Trip>,
  'updateExpense' : ActorMethod<
    [
      string,
      string,
      number,
      ExpenseCategory,
      string,
      ExternalBlob,
      [] | [string],
      string,
    ],
    undefined
  >,
  'updateTrip' : ActorMethod<
    [string, string, string, string, [] | [string]],
    undefined
  >,
  'uploadBillImage' : ActorMethod<[ExternalBlob], ExternalBlob>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];