/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExpenseCategory = IDL.Variant({
  'Food' : IDL.Null,
  'Travel' : IDL.Null,
  'Hotel' : IDL.Null,
  'Other' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Expense = IDL.Record({
  'id' : IDL.Text,
  'expenseDate' : IDL.Text,
  'title' : IDL.Text,
  'billImage' : ExternalBlob,
  'tripId' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'category' : ExpenseCategory,
  'amount' : IDL.Float64,
});
export const Trip = IDL.Record({
  'id' : IDL.Text,
  'endDate' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Opt(IDL.Text),
  'startDate' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addExpense' : IDL.Func(
      [
        IDL.Text,
        IDL.Float64,
        ExpenseCategory,
        IDL.Text,
        ExternalBlob,
        IDL.Opt(IDL.Text),
        IDL.Text,
      ],
      [Expense],
      [],
    ),
  'createTrip' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [Trip],
      [],
    ),
  'debugPrintTripsMap' : IDL.Func([], [], ['query']),
  'deleteExpense' : IDL.Func([IDL.Text], [], []),
  'deleteTrip' : IDL.Func([IDL.Text], [], []),
  'getAllTrips' : IDL.Func([], [IDL.Vec(Trip)], ['query']),
  'getExpensesByTripId' : IDL.Func([IDL.Text], [IDL.Vec(Expense)], ['query']),
  'getTripById' : IDL.Func([IDL.Text], [Trip], ['query']),
  'updateExpense' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        ExpenseCategory,
        IDL.Text,
        ExternalBlob,
        IDL.Opt(IDL.Text),
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateTrip' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'uploadBillImage' : IDL.Func([ExternalBlob], [ExternalBlob], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExpenseCategory = IDL.Variant({
    'Food' : IDL.Null,
    'Travel' : IDL.Null,
    'Hotel' : IDL.Null,
    'Other' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Expense = IDL.Record({
    'id' : IDL.Text,
    'expenseDate' : IDL.Text,
    'title' : IDL.Text,
    'billImage' : ExternalBlob,
    'tripId' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'category' : ExpenseCategory,
    'amount' : IDL.Float64,
  });
  const Trip = IDL.Record({
    'id' : IDL.Text,
    'endDate' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Opt(IDL.Text),
    'startDate' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addExpense' : IDL.Func(
        [
          IDL.Text,
          IDL.Float64,
          ExpenseCategory,
          IDL.Text,
          ExternalBlob,
          IDL.Opt(IDL.Text),
          IDL.Text,
        ],
        [Expense],
        [],
      ),
    'createTrip' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [Trip],
        [],
      ),
    'debugPrintTripsMap' : IDL.Func([], [], ['query']),
    'deleteExpense' : IDL.Func([IDL.Text], [], []),
    'deleteTrip' : IDL.Func([IDL.Text], [], []),
    'getAllTrips' : IDL.Func([], [IDL.Vec(Trip)], ['query']),
    'getExpensesByTripId' : IDL.Func([IDL.Text], [IDL.Vec(Expense)], ['query']),
    'getTripById' : IDL.Func([IDL.Text], [Trip], ['query']),
    'updateExpense' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          ExpenseCategory,
          IDL.Text,
          ExternalBlob,
          IDL.Opt(IDL.Text),
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateTrip' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'uploadBillImage' : IDL.Func([ExternalBlob], [ExternalBlob], []),
  });
};

export const init = ({ IDL }) => { return []; };